[Distribution]
Distribution=fedora
Release=44

[Build]
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Content]
Bootable=yes
Packages=
    bash
    cephadm
    ceph
    chrony
    coreutils
    dbus
    dnf
    kernel
    iproute
    logrotate
    podman
    systemd
    systemd-boot-unsigned
    systemd-networkd
    systemd-resolved
Bootloader=systemd-boot
RootPassword=hashed:
KernelCommandLine=selinux=0

[Host]
QemuArgs=-net bridge,br=virbr0 -net nic,model=virtio -device nvme,serial=osd1,drive=osd1
QemuDrives=osd1:8G
RuntimeNetwork=none
RuntimeScratch=yes
QemuKvm=yes
QemuMem=8G
QemuSmp=0
